project 'PuckHunt.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PuckHunt' do

  # Fixes required for pod specs to work with rn 0.42
  # https://github.com/airbnb/react-native-maps/issues/1078
  react_native_path = "../node_modules/react-native"
  pod "Yoga", :path => "#{react_native_path}/ReactCommon/yoga"
  pod "React", :path => react_native_path, :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'GoogleMaps'

#   target 'PuckHunt-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
# 
#   target 'PuckHuntTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

end

# target 'PuckHunt-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!
# 
#   # Pods for PuckHunt-tvOS
# 
#   target 'PuckHunt-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
# 
# end
