version: '2'
services:
  postgres:
    image: postgres:9.6.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./volumes/postgres-backups:/backups
